[package]
name = "ed25519_dalek_sign_message"
version = "0.1.0"
authors = ["phayes <patrick.d.hayes@gmail.com>"]
edition = "2018"

[dependencies]
sidefuzz = {git = "https://github.com/phayes/sidefuzz"}
rand = "0.6.5"
ed25519-dalek = "0.9.1"
sha2 = "0.8.0"